### What You Will Create:

- A series of NumPy arrays demonstrating different operations, ranging from simple array creation to more complex manipulations.

---

**🌟 Exercise 1 : Array Creation and Manipulation**

Instructions

Create a 1D NumPy array containing numbers from 0 to 9.

Expected Output:

`array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])`


In [1]:
import numpy as np

In [2]:
ex_1_arr = np.arange(10)
ex_1_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**🌟 Exercise 2 : Type Conversion and Array Operations**

Instructions

Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.

Expected Output:

`array([3, 2, 0, 1, 2])`


In [3]:
list_arr = [3.14, 2.17, 0, 1, 2]
ex_2_arr = np.array(list_arr)
ex_2_arr = ex_2_arr.astype(int)
ex_2_arr

array([3, 2, 0, 1, 2])

**🌟 Exercise 3 : Working with Multi-Dimensional Arrays**

Instructions

Create a 3x3 NumPy array with values ranging from 1 to 9.

Expected Output:

`array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])`


In [4]:
ex_3_mat = np.arange(1, 10).reshape(3, 3)
ex_3_mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**🌟 Exercise 4 : Creating Multi-Dimensional Array with Random Numbers**

Instructions

Create a 2D NumPy array of shape (4, 5) filled with random numbers.

Expected Output:

`array([[0.56, 0.85, 0.01, 0.42, 0.68],
       [0.22, 0.37, 0.73, 0.93, 0.39],
       [0.44, 0.03, 0.87, 0.02, 0.83],
       [0.78, 0.87, 0.98, 0.80, 0.46]])`


In [5]:
ex_4_mat = np.round(np.random.rand(4, 5), 2)
ex_4_mat

array([[0.33, 0.02, 0.52, 0.65, 0.56],
       [0.89, 0.87, 0.76, 0.99, 0.34],
       [0.46, 0.63, 0.5 , 0.25, 0.15],
       [0.19, 0.09, 0.66, 0.89, 0.43]])

**🌟 Exercise 5 : Indexing Arrays**

Instructions

Select the second row from a given 2D NumPy array.

Expected Output:

`array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])`


In [6]:
array = np.array([[21, 22, 23, 22, 22], [20, 21, 22, 23, 24], [21, 22, 23, 22, 22]])
array[1]

array([20, 21, 22, 23, 24])

**🌟 Exercise 6 : Reversing elements**

Instructions

Reverse the order of elements in a given 1D NumPy array (first element becomes last).

Expected Output:

`array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])`


In [7]:
ex_6_arr = ex_1_arr[::-1]
ex_6_arr

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

**🌟 Exercise 7 : Identity Matrix**

Instructions

Create a 4x4 identity matrix using NumPy.

Expected Output:

`array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])`


In [8]:
ex_7_mat = np.eye(4)
ex_7_mat

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**🌟 Exercise 8 : Simple Aggregate Funcs**

Instructions

Find the sum and average of a given 1D array.

Expected Output:

`Sum: 45, Average: 4.5`


In [9]:
ex_1_arr_sum = ex_1_arr.sum()
ex_1_arr_avg = ex_1_arr.mean()

print(f"Sum: {ex_1_arr_sum}, Average: {ex_1_arr_avg}")

Sum: 45, Average: 4.5


**🌟 Exercise 9 : Create Array and Change its Structure**

Instructions

Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.

Expected Output:

`array([[1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])`


In [10]:
ex_9_arr = np.arange(1, 21)
ex_9_mat = ex_9_arr.reshape(4, 5)
ex_9_mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

**🌟 Exercise 10 : Conditional Selection of Values**

Instructions

Extract all odd numbers from a given NumPy array.

Expected Output:

`array([1, 3, 5, 7, 9])`


In [11]:
ex_10_arr = ex_1_arr[ex_1_arr % 2 == 1]
ex_10_arr

array([1, 3, 5, 7, 9])